apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: web
  labels:
    app: employees
spec:
  containers:
  - name: webapp
    image: 979560716386.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
    ports:
    - containerPort: 80
    env:
    - name: DBHOST
      value: "10.244.0.5"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"
    - name: APP_COLOR
      value: "blue"
  imagePullSecrets:
    - name: ecr-secret